name: Empty format test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "test"

  format:
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'
    permissions:
      contents: write
    steps:
      - name: Generate hs-bot-gh-ap installation token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ secrets.HS_BOT_GH_AP_APP_ID }}
          private-key: ${{ secrets.HS_BOT_GH_AP_PRIVATE_KEY }}
      - uses: actions/checkout@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: git pull
      - run: |
          npx prettier --write "**/*.{md,yaml,yml,js}" --trailing-comma all --print-width 80 --single-quote true
          git --no-pager diff
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'style: re-format / npx prettier --write "**/*.{md,yaml,yml,js}"'
